rm(list=ls())
library(tidyverse)
library(readxl)
library(janitor)
library(stringr)
posns<-read_excel("./data/Positions Mar-23-2021.xlsx",sheet=2)
cash<-3134.01
posns<-clean_names(posns)
options<-posns %>% filter(security_type %in% c("Call","Put")) %>% arrange(quantity_position)
equities<-posns %>% filter(security_type %in% c("Eqty"))
risky_equities <- equities %>% filter(symbol %in% c("AAL","FNV"))   
long_options<-options %>% filter(quantity_position>0)
short_options<-options %>% filter(quantity_position<0)
long_options<- adorn_totals(long_options)
short_options<- adorn_totals(short_options)
equities<- adorn_totals(equities)
risky_equities<- adorn_totals(risky_equities)
total_eqty<-equities %>% filter(symbol=='Total') %>% select(position_dollar_value)
total_risky_eqty<-risky_equities %>% filter(symbol=='Total') %>% select(position_dollar_value)
total_long_opts<-long_options %>% filter(symbol=='Total') %>% select(position_dollar_value)
total_short_opts<-short_options %>% filter(symbol=='Total') %>% select(position_dollar_value)
acct_bal<-total_eqty+total_long_opts+total_short_opts+cash
total_opts<-abs(total_long_opts)+abs(total_short_opts)
opts_eqty_ratio<-total_opts/total_eqty
opts_nonriskeqty_ratio<-total_opts/(total_eqty-total_risky_eqty)
print(acct_bal)
print(total_eqty)
print(total_risky_eqty)
print(total_long_opts)
print(total_short_opts)
print(cash)
print(opts_eqty_ratio)
print(opts_nonriskeqty_ratio)
print(total_short_opts/cash)
print(total_short_opts/(cash+total_long_opts))
print(paste0("~'Free' Cash: ", round((1+total_short_opts/(cash+total_long_opts))*cash,2)))

